import { Pikachu, Charmander, Squirtle, Bulbasaur, Vulpix, Psyduck } from "./pokemon"

const pikachu = new Pikachu(50)
const charmander = new Charmander(50)
const squirtle = new Squirtle(50)
const bulbasaur = new Bulbasaur(50)
const vulpix = new Vulpix(50)
const psyduck = new Psyduck(50)

pikachu.getHP()
squirtle.getHP()
pikachu.attack(squirtle, 'thunderbolt')
pikachu.getHP()
squirtle.getHP()
squirtle.attack(pikachu, 'firebolt')
pikachu.getHP()
squirtle.getHP()
pikachu.attack(squirtle)
pikachu.getHP()
squirtle.getHP()
squirtle.attack(pikachu)
pikachu.getHP()
squirtle.getHP()
pikachu.attack(squirtle)
pikachu.getHP()
squirtle.getHP()
squirtle.attack(pikachu)
pikachu.getHP()
squirtle.getHP()